default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  username: myappd
  password: myapp
  encoding: unicode
  host: localhost
  pool: 5

test:
  <<: *default
  database: myapp_test
  username: myapp
  password: myapp
  encoding: unicode
  host: localhost
  pool: 5

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: myapp